services:
  - type: web
    name: recroom-node-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PUBLIC_BASE_URL
        sync: false
